# Generated by Django 4.2.15 on 2024-08-22 19:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('barisal', 'Barisal'), ('chittagong', 'Chittagong'), ('dhaka', 'Dhaka'), ('khulna', 'Khulna'), ('mymensingh', 'Mymensingh'), ('rajshahi', 'Rajshahi'), ('rangpur', 'Rangpur')], max_length=50, verbose_name='Division')),
                ('district', models.CharField(max_length=50, verbose_name='District')),
                ('thana', models.CharField(max_length=50, verbose_name='Thana')),
                ('post_code', models.CharField(max_length=50, verbose_name='Postal Code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('fmale', 'Fmale')], max_length=50, verbose_name='Gender')),
                ('account_type', models.CharField(choices=[('saveing', 'Saveing'), ('current', 'Current'), ('student', 'Student')], max_length=50, verbose_name='Account Type')),
                ('account_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(5)], verbose_name='Account Number')),
                ('account_balance', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(5)], verbose_name='Accoount Balance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
