# Generated by Django 4.2.15 on 2024-08-22 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_account_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Account Number'),
        ),
    ]
