# Generated by Django 4.2.15 on 2024-08-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('saveing', 'Saveing'), ('current', 'Current'), ('student', 'Student')], default=None, max_length=50, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('fmale', 'Fmale')], default=None, max_length=50, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='division',
            field=models.CharField(choices=[('barisal', 'Barisal'), ('chittagong', 'Chittagong'), ('dhaka', 'Dhaka'), ('khulna', 'Khulna'), ('mymensingh', 'Mymensingh'), ('rajshahi', 'Rajshahi'), ('rangpur', 'Rangpur')], default=None, max_length=50, verbose_name='Division'),
        ),
    ]
