# Generated by Django 4.2.15 on 2024-08-24 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0003_transaction_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositForm',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Transactions.transaction')),
            ],
            bases=('Transactions.transaction',),
        ),
    ]
