# Generated by Django 4.2.15 on 2024-08-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0004_depositform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.DeleteModel(
            name='DepositForm',
        ),
    ]
