# Generated by Django 4.2.15 on 2024-08-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0005_remove_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[(1, 'Deposit'), (2, 'Widthraw'), (3, 'Loan'), (4, 'Loan Paid')], max_length=12, null=True),
        ),
    ]
